package initproj

// Seed texts, byte for byte the heredocs of bin/hv-bootstrap, except MAP.md
// (G4 of the A9 rulings): it names `rota map query` and `rota map index`.

const backlogSeed = `# Backlog

## Bugs

## Features

## Tasks

## Completed
`

const knowledgeSeed = "# Knowledge\n\n" +
	"Durable learnings captured from sessions — gotchas, conventions, constraints, and hard-won debugging insights. Grouped by topic, newest first within each topic.\n\n" +
	"Use `/rota-learn` at the end of a session to capture new learnings. `/rota-work` consults this file when its topics are relevant to the task.\n\n" +
	"## Glossary\n\n" +
	"_(no terms yet — use `/rota-learn --term <name>` to capture project terminology)_\n"

const decisionsSeed = "# Decisions\n\n" +
	"Hard boundaries for this project. Each entry is a commitment, not a preference — re-read before proposing changes that touch its area.\n\n" +
	"Use `/rota-decide` to capture a new decision. `/rota-work`, `/rota-debug`, `/rota-plan`, `/rota-refactor`, `/rota-review`, and `/rota-vision` consult this file when its topics are relevant.\n"

const mapSeed = "# Project map\n\n" +
	"AI-facing index of subsystems. Detail files live in `.rota/map/<name>.md` and are loaded on demand via `rota map query <name>`. The thin always-on summary in `CLAUDE.md` is regenerated by `rota map index`.\n\n" +
	"Write `.rota/map/<name>.md` files describing subsystems as you discover them. Cycle skills (`/rota-work`, `/rota-debug`) bump `touched:` post-cycle on subsystems whose key files or entry points overlap the cycle's changes.\n"

const milestonesSeed = "# Milestones\n\n" +
	"_(no vision yet — run `/rota-vision` to brainstorm milestones)_\n\n" +
	"## Active milestones\n\n" +
	"_(none active — set with `/rota-vision`)_\n\n" +
	"## Milestones\n"

const countersSeed = `{"bugs":0,"features":0,"tasks":0,"milestones":0,"since_refactor":{"features":0,"bugs":0}}` + "\n"

const statusSeed = `{"active":[]}` + "\n"

const reposSeed = `{"repos":[]}` + "\n"

// configSeed is the old issues-only default, with the keys in schema order
// (G7): the order config.Keys lists them in, which is the order `rota config
// show` prints. The old helper wrote label, autoCreateLabel, filterMineOnly and
// then providers.
const configSeed = `{
  "issues": {
    "providers": {
      "github": true,
      "gitlab": true
    },
    "label": "in-progress",
    "autoCreateLabel": true,
    "filterMineOnly": false
  }
}
`
