package cli

// contractVerbs is every verb path the verb contract
// (docs/design/contract/) defines, one "### rota <path>" heading
// each, with argument and flag words dropped. TestContractVerbsMatchTheContract
// parses the contract and fails when this list drifts from it; the failure
// prints the list to paste here.
var contractVerbs = []string{
	"backlog archive",
	"backlog backfill",
	"backlog drift",
	"backlog ids",
	"backlog list",
	"backlog milestones",
	"backlog stale",
	"block",
	"block skills",
	"config check",
	"config fill",
	"config set",
	"config show",
	"debug counter clear",
	"debug counter fail",
	"debug counter inc-cycle",
	"debug counter init",
	"debug counter pass",
	"debug counter record-attempt",
	"debug counter show",
	"debug counter summary",
	"debug reset",
	"debug verdict",
	"decisions query",
	"design add",
	"design amend",
	"design list",
	"design put",
	"design rm",
	"design show",
	"doctor",
	"gate list",
	"git base",
	"git branch",
	"git guard clean",
	"git guard feature-branch",
	"git worktree-path",
	"glossary import",
	"glossary read",
	"glossary write",
	"hook install",
	"hook prompt",
	"hook session-start",
	"hook stop",
	"hook uninstall",
	"id next",
	"init",
	"init check",
	"init umbrella",
	"instructions init",
	"issues close",
	"issues imported",
	"issues label",
	"issues provider",
	"item claim",
	"item comment add",
	"item comment list",
	"item complete",
	"item create",
	"item field get",
	"item field list",
	"item field set",
	"item note add",
	"item note rm",
	"item note show",
	"item ready",
	"item release",
	"item reopen",
	"item rm",
	"item shipped",
	"item show",
	"item state",
	"keepalive run",
	"keepalive status",
	"knowledge add",
	"knowledge amend",
	"knowledge contradiction add",
	"knowledge contradiction clear",
	"knowledge contradiction has",
	"knowledge contradiction list",
	"knowledge hit",
	"knowledge query",
	"knowledge rename-topic",
	"knowledge replace",
	"knowledge stats",
	"knowledge tier get",
	"knowledge tier list",
	"knowledge tier set",
	"limit status",
	"limit watch",
	"map index",
	"map query",
	"map stats",
	"migrate hv",
	"migrate issues",
	"milestone active",
	"milestone add",
	"milestone index",
	"milestone list",
	"milestone overview",
	"milestone put",
	"milestone show",
	"milestone status",
	"orchestrate",
	"plan add",
	"plan list",
	"plan put",
	"plan rename-check",
	"plan rm",
	"plan show",
	"plan uncertain",
	"plan validate-docs",
	"projects",
	"proof add",
	"proof show",
	"qa index",
	"qa query",
	"reap",
	"refactor age",
	"refactor reset",
	"refactor targets",
	"release bump",
	"release changelog",
	"release close-milestone",
	"release host",
	"release milestone-check",
	"release notes",
	"release pending",
	"release publish",
	"release push",
	"release version",
	"repo resolve",
	"repo umbrella",
	"repo which",
	"review brief",
	"review queue",
	"review scaffolding",
	"review scope",
	"round architecture",
	"round assign",
	"round candidates",
	"round escalate check",
	"round escalate send",
	"round reclaim",
	"round reconcile",
	"round report",
	"round return",
	"round start",
	"round status",
	"round transfer",
	"round wait",
	"round watch",
	"round wind-down",
	"setup",
	"ship body",
	"ship merge",
	"ship pr",
	"ship pr-merge",
	"ship undo",
	"skills install",
	"skills status",
	"skills uninstall",
	"skills update",
	"spike add",
	"spike finish",
	"spike list",
	"spike show",
	"status add",
	"status handoff",
	"status rm",
	"status show",
	"statusline dump",
	"summary",
	"tracker call",
	"tracker suggest-upstream",
	"update",
	"verdict add",
	"verdict route",
	"verdict show",
	"version",
	"worker account assign",
	"worker account list",
	"worker account pick",
	"worker dispatch",
	"worker gate",
	"worker poll",
	"worker pool init",
	"worker pool list",
	"worker pool reap",
	"worker prompt-check",
	"worker reset",
	"worker session check",
	"worker session ensure",
	"worker train",
}
