// Package agents renders the per-harness subagent definitions rota emits for
// its three tier roles (#405): .claude/agents/rota-<role>.md and, when Codex is
// configured, .codex/agents/rota-<role>.toml. The files are generated from
// config, carry a header saying so, and are never written over a same-named
// file that lacks it.
package agents

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/l4ci/rota/internal/config"
	"github.com/l4ci/rota/internal/fsio"
	"github.com/l4ci/rota/internal/harness"
	"github.com/l4ci/rota/internal/rotatree"
	"github.com/l4ci/rota/internal/roundcfg"
)

// Marker is the phrase every generated file's header holds. A file without it
// was written by hand and is left alone.
const Marker = "generated by rota"

const (
	claudeDir = ".claude/agents"
	codexDir  = ".codex/agents"
)

// CodexEfforts are the model_reasoning_effort values every Codex model lists as
// supported. "max" and "ultra" exist on some models only, so a role asking for
// them is refused rather than written into a file that may not load.
var CodexEfforts = []string{"low", "medium", "high", "xhigh"}

// ExplorerTools is the Claude tool allowlist of the explorer role. Bash stays
// (git log, rg), so it is read-mostly rather than strictly read-only.
const ExplorerTools = "Read, Grep, Glob, Bash"

// Role is one role with its resolved models. CodexModel is "" when no Codex
// tier map is configured: the file then omits model and Codex picks its own.
type Role struct {
	Name        string
	Tier        string
	Effort      string
	ClaudeModel string
	CodexModel  string
}

// Spec is everything the files are rendered from.
type Spec struct {
	Roles []Role
	Codex bool // whether the .codex/agents files are emitted
}

// File is one file to write, relative to the project root.
type File struct{ Path, Content string }

// Status of one file against disk.
const (
	StatusCurrent = "current"
	StatusMissing = "missing"
	StatusDrift   = "drift"
	StatusForeign = "foreign" // exists without the generated header
)

// Entry is a file and how it compares to disk.
type Entry struct {
	File
	Status string
}

// Load reads the spec from the project config.
func Load(root string) (Spec, error) {
	set, err := roundcfg.Load(root)
	if err != nil {
		return Spec{}, err
	}
	cfg := config.Load(rotatree.Config(root))
	var sp Spec
	for _, name := range roundcfg.Roles {
		r := set.Roles[name]
		sp.Roles = append(sp.Roles, Role{
			Name: name, Tier: r.Tier, Effort: r.Effort,
			ClaudeModel: set.Model(harness.Claude, r.Tier),
			CodexModel:  set.Model(harness.Codex, r.Tier),
		})
	}
	sp.Codex = codexConfigured(cfg, set)
	return sp, nil
}

// codexConfigured is whether the project uses Codex at all: a Codex tier map, a
// named Codex home, a custom Codex command or Codex as the default worker kind.
func codexConfigured(cfg any, set roundcfg.Settings) bool {
	if set.Models[harness.Codex] != nil || set.WorkerKind == harness.Codex {
		return true
	}
	if len(config.CodexAccounts(cfg)) > 0 {
		return true
	}
	v, _ := config.Value(cfg, "work.codexCommand")
	s, _ := v.(string)
	return strings.TrimSpace(s) != ""
}

var descriptions = map[string]string{
	"explorer":    "Read-only discovery for rota workers: searching, reading and summarising code. Use for broad lookups; it must not edit files.",
	"implementer": "Writes code and tests for rota workers from a clear brief. Use for implementation that needs no new design.",
	"reasoner":    "Hard reasoning for rota workers: design, a tricky debugging hypothesis, an architecture call. Use sparingly.",
}

var instructions = map[string]string{
	"explorer":    "You explore a codebase and report what you found. Search and read; never edit or write files. Answer with file paths and line numbers, and say plainly what you could not find.",
	"implementer": "You implement a change from the brief you were given. Write the code and its tests, run the targeted checks for the files you touched, and report what changed. Stay inside the brief; if it is wrong or unclear, say so instead of guessing.",
	"reasoner":    "You work through a hard problem: a design choice, a debugging hypothesis, a tradeoff. State your assumptions, weigh the alternatives against the code, and end with one recommendation and what would change it.",
}

// Render returns the files for spec, Claude files first. A role effort Codex
// cannot express is an error naming the role and value; nothing is rendered.
func Render(sp Spec) ([]File, error) {
	var out []File
	for _, r := range sp.Roles {
		out = append(out, File{claudeDir + "/rota-" + r.Name + ".md", claudeFile(r)})
	}
	if sp.Codex {
		for _, r := range sp.Roles {
			if r.Effort != "" && !contains(CodexEfforts, r.Effort) {
				return nil, fmt.Errorf("%w: roles.%s.effort %q is not a Codex model_reasoning_effort (%s)", ErrEffort, r.Name, r.Effort, strings.Join(CodexEfforts, ", "))
			}
			out = append(out, File{codexDir + "/rota-" + r.Name + ".toml", codexFile(r)})
		}
	}
	return out, nil
}

func contains(l []string, s string) bool {
	for _, v := range l {
		if v == s {
			return true
		}
	}
	return false
}

func claudeFile(r Role) string {
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("name: rota-" + r.Name + "\n")
	b.WriteString("description: " + strconv.Quote(descriptions[r.Name]) + "\n")
	b.WriteString("model: " + r.ClaudeModel + "\n")
	if r.Effort != "" {
		b.WriteString("effort: " + r.Effort + "\n")
	}
	if r.Name == "explorer" {
		b.WriteString("tools: " + ExplorerTools + "\n")
	}
	b.WriteString("---\n")
	b.WriteString("<!-- " + Marker + " (rota agents write) from roles." + r.Name + " in .rota/config.json; do not edit -->\n\n")
	b.WriteString(instructions[r.Name] + "\n")
	return b.String()
}

func codexFile(r Role) string {
	var b strings.Builder
	b.WriteString("# " + Marker + " (rota agents write) from roles." + r.Name + " in .rota/config.json; do not edit\n")
	b.WriteString("name = " + strconv.Quote("rota-"+r.Name) + "\n")
	b.WriteString("description = " + strconv.Quote(descriptions[r.Name]) + "\n")
	if r.CodexModel != "" {
		b.WriteString("model = " + strconv.Quote(r.CodexModel) + "\n")
	}
	if r.Effort != "" {
		b.WriteString("model_reasoning_effort = " + strconv.Quote(r.Effort) + "\n")
	}
	if r.Name == "explorer" {
		b.WriteString("sandbox_mode = \"read-only\"\n")
	}
	b.WriteString("developer_instructions = \"\"\"\n" + instructions[r.Name] + "\n\"\"\"\n")
	return b.String()
}

// Compare renders the files and sets each one's status against disk under root.
func Compare(root string) ([]Entry, error) {
	sp, err := Load(root)
	if err != nil {
		return nil, err
	}
	files, err := Render(sp)
	if err != nil {
		return nil, err
	}
	var out []Entry
	for _, f := range files {
		e := Entry{File: f}
		b, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(f.Path)))
		switch {
		case errors.Is(err, os.ErrNotExist):
			e.Status = StatusMissing
		case err != nil:
			return nil, err
		case !strings.Contains(string(b), Marker):
			e.Status = StatusForeign
		case string(b) != f.Content:
			e.Status = StatusDrift
		default:
			e.Status = StatusCurrent
		}
		out = append(out, e)
	}
	return out, nil
}

// ErrEffort marks a role effort that Codex cannot express.
var ErrEffort = errors.New("effort not supported by Codex")

// ErrForeign marks a refusal to overwrite a file rota did not generate.
var ErrForeign = errors.New("not generated by rota")

// Write brings every file up to date and returns the entries with the status
// they had before. It writes nothing when any target is a foreign file.
func Write(root string) ([]Entry, error) {
	es, err := Compare(root)
	if err != nil {
		return nil, err
	}
	var foreign []string
	for _, e := range es {
		if e.Status == StatusForeign {
			foreign = append(foreign, e.Path)
		}
	}
	if len(foreign) > 0 {
		return es, fmt.Errorf("%w: %s (move it aside or delete it, then rerun)", ErrForeign, strings.Join(foreign, ", "))
	}
	for _, e := range es {
		if e.Status == StatusCurrent {
			continue
		}
		if l := symlinkIn(root, e.Path); l != "" {
			return es, fmt.Errorf("%w: %s is a symlink; refusing to write through it", ErrForeign, l)
		}
		p := filepath.Join(root, filepath.FromSlash(e.Path))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			return es, err
		}
		if err := fsio.WriteFileAtomic(p, []byte(e.Content)); err != nil {
			return es, err
		}
	}
	return es, nil
}

// symlinkIn returns the first path component of rel under root that is a
// symlink, "" when none is, so a checked-in link cannot send a write outside
// the project.
func symlinkIn(root, rel string) string {
	cur := root
	for _, part := range strings.Split(rel, "/") {
		cur = filepath.Join(cur, part)
		if fi, err := os.Lstat(cur); err == nil && fi.Mode()&os.ModeSymlink != 0 {
			return filepath.ToSlash(strings.TrimPrefix(cur, root+string(filepath.Separator)))
		}
	}
	return ""
}

// Problems lists the files that are missing or have drifted, as one line each
// for `rota doctor`; a config or render error is one line too.
func Problems(root string) []string {
	es, err := Compare(root)
	if err != nil {
		return []string{err.Error()}
	}
	var out []string
	for _, e := range es {
		if e.Status != StatusCurrent {
			out = append(out, e.Path+": "+e.Status)
		}
	}
	return out
}
